name: unify-core
version: '1.0-SNAPSHOT'
main: me.jordanfails.unify.UnifyCore
api-version: '1.18'
author: "JordanFails"
website: "https://github.com/JordanFails"
softdepend: [WorldGuard, NBTAPI]
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.2.21
  - org.jetbrains.kotlin:kotlin-reflect:2.2.21
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.2.21
  - org.jetbrains.kotlin:kotlin-reflect:2.2.21